
# remove .test to run docker image container with the given env. If docker image is made with the env_file, then the project env will be used in the image rather than the config file in our app
version: "3.7"
services:
  api-portal:
    env_file: .env
    build: / # tells Docker where the Dockerfile is for our image from workdir in dockerfile
    ports:
      - "3000:3000"
    expose:
      - "3000"
    # restart: always

